[package]
name = "const_list"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DouglasDwyer/const_list"
readme = "README.md"
description = """
A tiny linked list usable in const contexts.
"""